export type {
  BaseInputProps,
  SelectSlotProps,
  MultiSelectSlotProps,
  TextInputSlotProps,
  NumberInputSlotProps,
  DatePickerSlotProps,
  SwitchSlotProps,
  ButtonSlotProps,
  WrapperSlotProps,
  ErrorMessageSlotProps,
  LabelSlotProps,
  ValueModeToggleSlotProps,
  ComponentSlots,
  PartialComponentSlots,
} from './slots';
